Card.create(question: "The french dude", answer: "Quentin")
Card.create(question: "The wizard", answer: "Topher")
Card.create(question: "The tall guy", answer: "Tim")
Card.create(question: "Papa Poison", answer: "Stephen")
Card.create(question: "Glenn", answer: "Matthew")
Card.create(question: "Mozzarella", answer: "Brittany")
Card.create(question: "Cool first name", answer: "Strand")
Card.create(question: "Tsunami", answer: "Johnny")
Card.create(question: "*insert meow here*", answer: "Rao Rao")
Card.create(question: "Sweet awesomeness", answer: "Shadi")
Card.create(question: "Led Zepplin", answer: "Phil")
Card.create(question: "Apparently a god of pool", answer: "Sherif")
Card.create(question: "Thinks farting is hilarious", answer: "Armondo")